### ISSUE TITLE
Setting enabled false doesn't work

### ISSUE THREAD

**Issue by dac388** [cloudposse/terraform-aws-route53-alias#20]
As stated in title.

**Comment by nitrocode** [comment]
@dac388 it looks like this was added in 2018 https://github.com/cloudposse/terraform-aws-route53-alias/pull/13

Do you still experience the issue with the latest version ? From the code, it looks like all the resources have the `module.this.enabled` toggle

**Comment by korenyoni** [comment]
Going to close this because by all accounts it should no longer be happening.
